dist: xenial

language: python
cache: pip
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy
env:
  TOXENV=py

before_install:
  - pyenv versions

install:
  - pip install tox

script:
  - tox

after_success:
  - tox -e coverage,codecov
